###

POST http://localhost:8080/oauth/token?username=user_1&password=123456&grant_type=password&scope=select&client_id=client_2&client_secret=123456 HTTP/1.1

###

POST http://localhost:8080/oauth/token?grant_type=client_credentials&scope=select&client_id=client_1&client_secret=123456 HTTP/1.1

###

POST http://localhost:8080/oauth/authorize HTTP/1.1

###